version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: ${CONTAINER_NAME:-mongodb}
    volumes:
    - ./data:/data/db
    ports:
    - ${DB_HOST_PORT}:27017
    environment:
    - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
    restart: always
  mongoexpress:
    image: mongo-express:latest
    container_name: ${CONTAINER_NAME}
    ports:
    - ${EXPRESS_HOST_PORT}:8081
    environment:
    - ME_CONFIG_BASICAUTH_PASSWORD=${WEB_PASSWORD}
    - ME_CONFIG_BASICAUTH_USERNAME=${WEB_USER}
    - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
    - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
    - ME_CONFIG_MONGODB_PORT=27017
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_OPTIONS_EDITORTHEME=${EDITOR_THEME}
    depends_on:
    - mongodb
    restart: always
