version: '3'

services:
  mongodb:
    container_name: ${CONTAINER_NAME:-mongodb}
    image: mongo:latest
    ports:
      - ${MONGODB_PORT:-27017}:27017
    networks:
      - mongodb
    volumes:
      - ./data:/data/db

networks:
  mongodb:
    external: true